=== GSA/dcat-us/jsonschema/definitions/RightsStatement.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://resources.data.gov/dcat-us/3.0.0/definitions/rightsstatement",
    "title": "RightsStatement",
    "description": "A statement about rights held with respect to another item",
    "type": "object",
    "properties": {
        "@id": {
            "type": "string",
            "format": "iri"
        },
        "@type": {
            "type": "string",
            "default": "RightsStatement"
        },
        "attributionText": {
            "title": "attribution text",
            "description": "The custom attribution text for the rights statement",
            "type": [
                "null",
                "string"
            ]
        },
        "attributionTextMap": {
            "description": "Language map for attribution text. E.g. {'es': 'spanish words', 'fr': 'french words'}",
            "type": [
                "null",
                "object"
            ]
        }
    },
    "required": []
}

=== GSA/dcat-us/jsonschema/examples/RightsStatement/good/complete_example.json
{
  "@id": "https://example.gov/rights-statements/public-domain",
  "@type": "RightsStatement",
  "attributionText": "U.S. Government Work - This dataset is in the public domain within the United States. Attribution is requested but not required.",
  "attributionTextMap": {
    "es": "Trabajo del Gobierno de EE. UU. - Este conjunto de datos es de dominio público dentro de los Estados Unidos.",
    "fr": "Travail du gouvernement américain - Ce jeu de données est dans le domaine public aux États-Unis."
  }
}
